name: CI-CD
on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v4.1.1
      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
          
      - name: Criação da Imagem docker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            rafaelsdomingos/app1:v${{ github.run_number }}
            rafaelsdomingos/app1:latest

  CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Pull da imagem do dockerhub
        run: docker pull rafaelsdomingos/app1:latest
      - name: Restart do docker-compose para atualizar o container com a nova imagem
        run: cd ~ubuntu/docker/app1 && docker-compose restart
